export class Post {
  constructor(
    public ID: number,
    public site_ID: number,
    public author: any,
    public date: string,
    public modified: string,
    public title: string,
    public URL: string,
    public short_URL: string,
    public content: string,
    public excerpt: string,
    public slug: string,
    public guid: string,
    public status: string,
    public sticky: boolean,
    public password: string,
    public parent: any,
    public type: string,
    public discussion: any,
    public likes_enabled: boolean,
    public sharing_enabled: boolean,
    public like_count: number,
    public i_like: boolean,
    public is_reblogged: boolean,
    public is_following: boolean,
    public global_ID: string,
    public featured_image: string,
    public post_thumbnail: any,
    public format: string,
    public geo: any,
    public menu_order: number,
    public page_template: string,
    public publicize_URLs: any[],
    public terms: any,
    public tags: any,
    public categories: any,
    public attachments: any,
    public attachment_count: number,
    public metadata: any[],
    public meta: any,
    public capabilities: any,
    public other_URLs: any,
    public opened: boolean = false,
    public comments_loading: boolean = false,
    public comments_load: boolean = false,
    public comments?: Comment[],
  ) {
  }
}
